apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: your-private-registry.com/your-app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-registry-secret
