apiVersion: v1
kind: Config

clusters:
- name: prod
  cluster:
    server: https://<PROD_API_SERVER>
    certificate-authority-data: <BASE64_ENCODED_PROD_CA>

- name: dev
  cluster:
    server: https://<DEV_API_SERVER>
    certificate-authority: <PATH_OF_THE_CERT_IN_SERVER>

users:
- name: prod-user
  user:
    client-certificate-data: <BASE64_ENCODED_PROD_USER_CRT>
    client-key-data: <BASE64_ENCODED_PROD_USER_KEY>

- name: dev-user
  user:
    client-certificate: <PATH_OF_THE_DEV_USER_CERT_IN_SERVER>
    client-key: <PATH_OF_THE_DEV_USER_CERT_IN_SERVER>


contexts:
- name: prod-context
  context:
    cluster: prod
    user: prod-user

- name: dev-context
  context:
    cluster: dev
    user: dev-user
    namespace: dev-ns #Mentioning namespace for the dev-user

current-context: dev-context
