apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo-namespace
  name: dev-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  resourceNames: ["my-app-pod"]  #Optional: specify if needed
  verbs: ["create","update", "delete", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmap"]
  verbs: ["create"]  
  
