apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi 
    persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0abcd1234ef567890
    fsType: ext4
