apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: myuser-csr
spec:
  request: <BASE64_ENCODED_CSR_HERE> #cat <csr-file> | base64 -w 0
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # Optional: 1 day
  usages:
    - digital signature
    - key encipherment
    - client auth
